name: Deploy to AWS App Runner

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: 'Debug: List files in current directory'
      run: ls -la

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Deploy to App Runner Image
      id: deploy-apprunner
      uses: awslabs/amazon-app-runner-deploy@main
      with:
        service: ${{ secrets.APP_RUNNER_SERVICE_NAME }}
        image: ${{ steps.build-image.outputs.image }}
        access-role-arn: ${{ secrets.ROLE_ARN }}
        region: ${{ secrets.AWS_REGION }}
        cpu: 1
        memory: 2
        wait-for-service-stability-seconds: 1200
        port: 8080
        branch: 'main'

    - name: App Runner URL
      run: echo "App runner URL ${{ steps.deploy-apprunner.outputs.service-url }}"
